[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
curve_launchpad = "HP1AdWRTGQbSAG6CXne7gGXsUzPnor8WfvxDuMvFaNAM"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 15000
shutdown_wait = 12000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "metaplex_metadata.so"
